### ISSUE TITLE
Your commit messages are all in the wrong tense!

### ISSUE THREAD

**Issue by zach-youssef** [Team1100/FRCInfiniteRecharge#64]
Hello Team 1100. It's me, the ghost of 1100 past.

Long ago, in the distant year of 2017, I was the head of the software subteam. Now, I'm a 5th year at Northeastern reading your code to entertain myself during a boring lecture on Cloud Computing.

Now, instead of commenting on anything actually useful, I want to impart some wisdom on git conventions.

Instead of writing, "adds so and so functionality" write "Add so and so". "Fix so and so". "Remove so and so" This is called the imperative tense. 

Feel free to close this issue without any action. I'm an old man, and you are young.

**Comment by snowpuppy** [comment]
Greetings ghost of 1100 past. I acknowledge that you are correct. The general standard for commit message tense does seem to be the imperative tense, and I am the guilty party for advising participants to use the present tense.

While it is not standard, I find that I prefer the present tense. It seems strange to me that a commit message summary should be "telling" me what to do, as it does with the imperative tense. However, if written in the present tense, the commit message summary tells me what it does. Effectively, it answers the question "What does this commit do?". This commit "adds so and so functionality". :)

**Comment by zach-youssef** [comment]
Hello 1100 future. I appreciate your response.

That is a solid argument. At the end of the day, if you have a justifiable reason to do something, don't let a curmudgeon like me stop you (as long as the repo is consistent)!

As a follow up, the imperative tense doesn't come from the commit telling _you_ what to do, but rather the commit is "telling" the code-base what to do.

If you (or anyone on the team) have any questions about what life is like as a Software Engineer or Computer Science student,  feel free to reach out at my [personal email](zacharysamiyoussef@gmail.com).

We're still a few months out, but enjoy the season!
